### ISSUE TITLE
Implement search by criteria service

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/devon4node#14]
### Description of issue / expected enhacement /Comments

Currently, we have a `getTodos` service implemented [here](https://github.com/devonfw/devon4node/blob/develop/template/src/todo/todo.controller.ts#L35) which returns the complete list of `Todos` elements. Unfortunately, there is no service implemented for searching `Todo` items by some criteria.

I don't think it would be hard to implement this and it would be very interesting for our current devon4ng client application, which contains a search by criteria.

**Comment by dario-rodriguez** [comment]
Hello Jaime,

The todo example is out of date and needs to be refactored.

Related to search criteria: we should give a try to nest crud, and they already have implemented the filter that you are requesting. https://docs.nestjs.com/recipes/crud

Anyway, it needs to be discussed. But, using the query to filter (instead of body) is the approach that I most like. It will make our life easier when we need to cache the request.

Kind regards

**Comment by jdiazgon** [comment]
> But, using the query to filter (instead of body) is the approach that I most like

I have created a pull request in order to address this issue, I think that I have followed your approach. You can take a look [here](https://github.com/devonfw/devon4node/pull/15/files#diff-182a30eee2b78085423ac4cc5501e73bR40) and give me any suggestion :)
